
export const constants = {
  SAVE_TREATMENT_SUCCESS: 'SAVE_TREATMENT_SUCCESS',
  SAVE_TREATMENT_REQUEST: 'SAVE_TREATMENT_REQUEST',
  SAVE_TREATMENT_FAILURE: 'SAVE_TREATMENT_FAILURE',

  FETCH_TREATMENT_REQUEST: 'FETCH_TREATMENT_REQUEST',
  FETCH_TREATMENT_SUCCESS: 'FETCH_TREATMENT_SUCCESS',
  FETCH_TREATMENT_FAILURE: 'FETCH_TREATMENT_FAILURE',

  UPDATE_TREATMENT_REQUEST: 'UPDATE_TREATMENT_REQUEST',
  UPDATE_TREATMENT_SUCCESS: 'UPDATE_TREATMENT_SUCCESS',
  UPDATE_TREATMENT_FAILURE: 'UPDATE_TREATMENT_FAILURE',

  UPDATE_TREATMENT_MEDICINE_REQUEST: 'UPDATE_TREATMENT_MEDICINE_REQUEST',
  UPDATE_TREATMENT_MEDICINE_SUCCESS: 'UPDATE_TREATMENT_MEDICINE_SUCCESS',
  UPDATE_TREATMENT_MEDICINE_FAILURE: 'UPDATE_TREATMENT_MEDICINE_FAILURE',

  UPDATE_MEDICINE_FROM_TREATMENT_REQUEST: 'UPDATE_MEDICINE_FROM_TREATMENT_REQUEST',
  UPDATE_MEDICINE_FROM_TREATMENT_SUCCESS: 'UPDATE_MEDICINE_FROM_TREATMENT_SUCCESS',
  UPDATE_MEDICINE_FROM_TREATMENT_FAILURE: 'UPDATE_MEDICINE_FROM_TREATMENT_FAILURE',

  DELETE_MEDICINE_FROM_TREATMENT_REQUEST: 'DELETE_MEDICINE_FROM_TREATMENT_REQUEST',
  DELETE_MEDICINE_FROM_TREATMENT_SUCCESS: 'DELETE_MEDICINE_FROM_TREATMENT_SUCCESS',
  DELETE_MEDICINE_FROM_TREATMENT_FAILURE: 'DELETE_MEDICINE_FROM_TREATMENT_FAILURE',

  DELETE_TREATMENT_REQUEST: 'DELETE_TREATMENT_REQUEST',
  DELETE_TREATMENT_SUCCESS: 'DELETE_TREATMENT_SUCCESS',
  DELETE_TREATMENT_FAILURE: 'DELETE_TREATMENT_FAILURE',


};
