
export const constants = {
  SET_PATIENT_NAME: 'SET_PATIENT_NAME',
  SET_PATIENT_AGE: 'SET_PATIENT_AGE',
  SET_PATIENT_SEX: 'SET_PATIENT_SEX',
  SET_PATIENT_MOBILE: 'SET_PATIENT_MOBILE',
  SET_PATIENT_EMAIL: 'SET_PATIENT_EMAIL',
  SET_PATIENT_PATIENTID: 'SET_PATIENT_PATIENTID',


  SET_PATIENT_OE: 'SET_PATIENT_OE',
  SET_PATIENT_DIAGNOSIS: 'SET_PATIENT_DIAGNOSIS',
  SET_PATIENT_CC: 'SET_PATIENT_CC',
  SET_PATIENT_TESTS: 'SET_PATIENT_TESTS',
  SET_PATIENT_ADVICE: 'SET_PATIENT_ADVICE',
  SET_PATIENT_FOLLOWUPDATE: 'SET_PATIENT_FOLLOWUPDATE',

  SET_PATIENT_MEDICINE: 'SET_PATIENT_MEDICINE',
  DELETE_PATIENT_MEDICINE: 'DELETE_PATIENT_MEDICINE',
  UPDATE_PATIENT_MEDICINE_NAME: 'UPDATE_PATIENT_MEDICINE_NAME',
  UPDATE_PATIENT_MEDICINE_STRENGTH: 'UPDATE_PATIENT_MEDICINE_STRENGTH',
  UPDATE_PATIENT_MEDICINE_TYPE: 'UPDATE_PATIENT_MEDICINE_TYPE',
  UPDATE_PATIENT_MEDICINE_FREQUENCY: 'UPDATE_PATIENT_MEDICINE_FREQUENCY',
  UPDATE_PATIENT_MEDICINE_REMARK: 'UPDATE_PATIENT_MEDICINE_REMARK',

  UPDATE_PATIENT_OE: 'UPDATE_PATIENT_OE',
  UPDATE_PATIENT_DIAGNOSIS: 'UPDATE_PATIENT_DIAGNOSIS',
  UPDATE_PATIENT_CC: 'UPDATE_PATIENT_CC',
  UPDATE_PATIENT_TESTS: 'UPDATE_PATIENT_TESTS',
  UPDATE_PATIENT_ADVICE: 'UPDATE_PATIENT_ADVICE',
  UPDATE_PATIENT_FOLLOWUPDATE: 'UPDATE_PATIENT_FOLLOWUPDATE',



  DELETE_ITEM_PATIENT_MEDICINE: 'DELETE_ITEM_PATIENT_MEDICINE',
  DELETE_ITEM_PATIENT_OE: 'DELETE_ITEM_PATIENT_OE',
  DELETE_ITEM_PATIENT_DIAGNOSIS: 'DELETE_ITEM_PATIENT_DIAGNOSIS',
  DELETE_ITEM_PATIENT_CC: 'DELETE_ITEM_PATIENT_CC',
  DELETE_ITEM_PATIENT_TESTS: 'DELETE_ITEM_PATIENT_TESTS',
  DELETE_ITEM_PATIENT_ADVICE: 'DELETE_ITEM_PATIENT_ADVICE',
  DELETE_ITEM_PATIENT_FOLLOWUPDATE: 'DELETE_ITEM_PATIENT_FOLLOWUPDATE',


  PATIENT_SAVE_REQUEST:'PATIENT_SAVE_REQUEST',
  PATIENT_SAVE_SUCCESS: 'PATIENT_SAVE_SUCCESS',
  PATIENT_SAVE_FAILURE: 'PATIENT_SAVE_FAILURE',

  PATIENT_FETCH_REQUEST:'PATIENT_FETCH_REQUEST',
  PATIENT_FETCH_SUCCESS: 'PATIENT_FETCH_SUCCESS',
  PATIENT_FETCH_FAILURE: 'PATIENT_FETCH_FAILURE'
};
